---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-api-service
  namespace: {{ .Values.appNamespace }}
  labels:
    app: {{ .Values.labels.app }}
    env: {{ .Values.labels.env }}
    tier: {{ .Values.labels.tier }}
    module: {{ .Values.labels.module }}
    svc: {{ .Values.labels.svc }}
spec:
  selector:
    app: {{ .Values.labels.app }}
    env: {{ .Values.labels.env }}
    tier: {{ .Values.labels.tier }}
    module: {{ .Values.labels.module }}
    svc: {{ .Values.labels.svc }}
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-api-deployment
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.api: glob:{{ .Values.fluxTag }}-*
  namespace: {{ .Values.appNamespace }}
  labels:
    app: {{ .Values.labels.app }}
    env: {{ .Values.labels.env }}
    tier: {{ .Values.labels.tier }}
    module: {{ .Values.labels.module }}
    svc: {{ .Values.labels.svc }}
spec:
  replicas: 1
  selector:
    matchLabels:
    app: {{ .Values.labels.app }}
    env: {{ .Values.labels.env }}
    tier: {{ .Values.labels.tier }}
    module: {{ .Values.labels.module }}
    svc: {{ .Values.labels.svc }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        env: {{ .Values.labels.env }}
        tier: {{ .Values.labels.tier }}
        module: {{ .Values.labels.module }}
        svc: {{ .Values.labels.svc }}
    spec:
      volumes:
      - name: {{ .Values.appName }}-api-keys-config
        configMap:
          name: {{ .Values.appName }}-api-keys-config
      containers:
      - name: api
        image: {{ .Values.imageTag }}
        ports:
        - containerPort: 9000
        args:
        - -c
        - (composer install || true) && (php artisan config:cache || true) && (php
          artisan l5-swagger:generate || true) && (php artisan migrate || true) &&
          php-fpm
        command: ["/bin/bash"]
        envFrom:
        - configMapRef:
            name: {{ .Values.appName }}-api-config
        volumeMounts:
        - name: {{ .Values.appName }}-api-keys-config
          mountPath: /var/www/storage/oauth-private.key
          subPath: oauth-private.key
        - name: {{ .Values.appName }}-api-keys-config
          mountPath: /var/www/storage/oauth-public.key
          subPath: oauth-public.key
