apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-index-config
  namespace: {{ .Values.appNamespace }}
  labels:
    app: {{ .Values.labels.app }}
    env: {{ .Values.labels.env }}
    tier: {{ .Values.labels.tier }}
    module: {{ .Values.labels.module }}
    svc: {{ .Values.labels.svcNginx }}
data:
  index.php: |
    <?php
    define('LARAVEL_START', microtime(true));
    require __DIR__.'/../vendor/autoload.php';
    $app = require_once __DIR__.'/../bootstrap/app.php';
    $kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);
    $response = $kernel->handle(
        $request = Illuminate\Http\Request::capture()
    );
    $response->send();
    $kernel->terminate($request, $response);
