---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-nginx-service
  namespace: {{ .Values.appNamespace }}
  labels:
    app: {{ .Values.labels.app }}
    env: {{ .Values.labels.env }}
    tier: {{ .Values.labels.tier }}
    module: {{ .Values.labels.module }}
    svc: {{ .Values.labels.svcNginx }}
spec:
  selector:
    app: {{ .Values.labels.app }}
    env: {{ .Values.labels.env }}
    tier: {{ .Values.labels.tier }}
    module: {{ .Values.labels.module }}
    svc: {{ .Values.labels.svcNginx }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-nginx-deployment
  namespace: {{ .Values.appNamespace }}
  labels:
    app: {{ .Values.labels.app }}
    env: {{ .Values.labels.env }}
    tier: {{ .Values.labels.tier }}
    module: {{ .Values.labels.module }}
    svc: {{ .Values.labels.svcNginx }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
      env: {{ .Values.labels.env }}
      tier: {{ .Values.labels.tier }}
      module: {{ .Values.labels.module }}
      svc: {{ .Values.labels.svcNginx }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        env: {{ .Values.labels.env }}
        tier: {{ .Values.labels.tier }}
        module: {{ .Values.labels.module }}
        svc: {{ .Values.labels.svcNginx }}
    spec:
      volumes:
        - name: {{ .Values.appName }}-index-config
          configMap:
            name: {{ .Values.appName }}-index-config

        - name: {{ .Values.appName }}-nginx-config
          configMap:
            name: {{ .Values.appName }}-nginx-config

      containers:
        - name: nginx
          image: nginx:1.18.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: {{ .Values.appName }}-nginx-config
              mountPath: /etc/nginx/conf.d
            - name: {{ .Values.appName }}-index-config
              mountPath: /var/www/public
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1
              memory: 600Mi
